/*
 * Copyright (c) 1997-1999 Massachusetts Institute of Technology
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * Generated by FFTW genfft and distributed under GNU GPL v2 or later.
 * Do not edit by hand; regenerate with tools/gen_dct_codelets.sh.
 */
/* Generated by: /tmp/fftw3/genfft/gen_r2r.native -fma -simd -vneg -compact -variables 4 -pipeline-latency 4 -redft10 -n 12 -name nss_dct12_fwd_is16 -standalone -noloop -with-istride 16 -with-ostride 16 -with-ivstride 1 -with-ovstride 1 -unitary -normsqr 24 */

/*
 * This function contains 46 FP additions, 28 FP multiplications,
 * (or, 30 additions, 12 multiplications, 16 fused multiply/add),
 * 29 stack variables, 7 constants, and 24 memory accesses
 */
template <class D>
static HWY_INLINE void nss_dct12_fwd_is16(D d, const R * I, R * O)
{
DVK(KP408248290, +0.408248290463863016366214012450981898660991247);
DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
DVK(KP288675134, +0.288675134594812882254574390250978727823800876);
DVK(KP414213562, +0.414213562373095048801688724209698078569671875);
DVK(KP377172239, +0.377172239742285770598670967238756190371511200);
DVK(KP353553390, +0.353553390593273762200422181052424519642417969);
DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
{
{
V T7, Tm, TH, TG, Tt, Tq, Te, Th, TE, TD, Tv, Tk;
{
V To, Tr, T3, Ts, T6, Tp;
To = LD(&(I[64]), 1, &(I[0]));
Tr = LD(&(I[112]), 1, &(I[16]));
{
V T1, T2, T4, T5;
T1 = LD(&(I[0]), 1, &(I[0]));
T2 = LD(&(I[128]), 1, &(I[0]));
T3 = VSUB(T1, T2);
Ts = VADD(T2, T1);
T4 = LD(&(I[176]), 1, &(I[16]));
T5 = LD(&(I[48]), 1, &(I[16]));
T6 = VSUB(T4, T5);
Tp = VADD(T5, T4);
}
T7 = VADD(T3, T6);
Tm = VSUB(T3, T6);
TH = VADD(To, Tp);
TG = VADD(Tr, Ts);
Tt = VFMS(LDK(KP500000000), Ts, Tr);
Tq = VFMS(LDK(KP500000000), Tp, To);
}
{
V Tf, Ti, Ta, Tg, Td, Tj;
Tf = LD(&(I[16]), 1, &(I[16]));
Ti = LD(&(I[160]), 1, &(I[0]));
{
V T8, T9, Tb, Tc;
T8 = LD(&(I[144]), 1, &(I[16]));
T9 = LD(&(I[96]), 1, &(I[0]));
Ta = VSUB(T8, T9);
Tg = VADD(T8, T9);
Tb = LD(&(I[32]), 1, &(I[0]));
Tc = LD(&(I[80]), 1, &(I[16]));
Td = VSUB(Tb, Tc);
Tj = VADD(Tb, Tc);
}
Te = VADD(Ta, Td);
Th = VFNMS(LDK(KP500000000), Tg, Tf);
TE = VADD(Ti, Tj);
TD = VADD(Tf, Tg);
Tv = VSUB(Td, Ta);
Tk = VFNMS(LDK(KP500000000), Tj, Ti);
}
{
V TJ, TK, TF, TI;
ST(&(O[64]),VMUL(LDK(KP353553390), VSUB(T7, Te)),1,&(O[0]));
TJ = VSUB(TG, TH);
TK = VSUB(TD, TE);
ST(&(O[48]),VMUL(LDK(KP377172239), VFMA(LDK(KP414213562), TK, TJ)),1,&(O[16]));
ST(&(O[144]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP414213562), TJ, TK))),1,&(O[16]));
TF = VADD(TD, TE);
TI = VADD(TG, TH);
ST(&(O[0]),VMUL(LDK(KP288675134), VADD(TF, TI)),1,&(O[0]));
ST(&(O[96]),VMUL(LDK(KP288675134), VSUB(TI, TF)),1,&(O[0]));
{
V TC, Tz, TA, TB;
TC = VADD(Te, T7);
Tz = VADD(Th, Tk);
TA = VADD(Tt, Tq);
TB = VADD(Tz, TA);
ST(&(O[160]),VNEG(VMUL(LDK(KP288675134), VFNMS(LDK(KP866025403), TC, TB))),1,&(O[0]));
ST(&(O[128]),VMUL(LDK(KP408248290), VSUB(TA, Tz)),1,&(O[0]));
ST(&(O[32]),VMUL(LDK(KP288675134), VFMA(LDK(KP866025403), TC, TB)),1,&(O[0]));
}
{
V Tn, Ty, Tw, Tx, Tl, Tu;
Tl = VSUB(Th, Tk);
Tn = VFMA(LDK(KP866025403), Tm, Tl);
Ty = VFNMS(LDK(KP866025403), Tm, Tl);
Tu = VSUB(Tq, Tt);
Tw = VFNMS(LDK(KP866025403), Tv, Tu);
Tx = VFMA(LDK(KP866025403), Tv, Tu);
ST(&(O[16]),VMUL(LDK(KP377172239), VFNMS(LDK(KP414213562), Tw, Tn)),1,&(O[16]));
ST(&(O[112]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP414213562), Tx, Ty))),1,&(O[16]));
ST(&(O[176]),VNEG(VMUL(LDK(KP377172239), VFMA(LDK(KP414213562), Tn, Tw))),1,&(O[16]));
ST(&(O[80]),VNEG(VMUL(LDK(KP377172239), VFMA(LDK(KP414213562), Ty, Tx))),1,&(O[16]));
}
}
}
}
VLEAVE();}

