/*
 * Copyright (c) 1997-1999 Massachusetts Institute of Technology
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * Generated by FFTW genfft and distributed under GNU GPL v2 or later.
 * Do not edit by hand; regenerate with tools/gen_dct_codelets.sh.
 */
/* Generated by: /tmp/fftw3/genfft/gen_r2r.native -fma -simd -vneg -compact -variables 4 -pipeline-latency 4 -redft01 -n 12 -name nss_dct12_inv_is16 -standalone -noloop -with-istride 16 -with-ostride 16 -with-ivstride 1 -with-ovstride 1 -unitary -normsqr 24 */

/*
 * This function contains 46 FP additions, 49 FP multiplications,
 * (or, 9 additions, 12 multiplications, 37 fused multiply/add),
 * 28 stack variables, 9 constants, and 24 memory accesses
 */
template <class D>
static HWY_INLINE void nss_dct12_inv_is16(D d, const R * I, R * O)
{
DVK(KP937379142, +0.937379142311347477529284336220916609359196770);
DVK(KP377172239, +0.377172239742285770598670967238756190371511200);
DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
DVK(KP923879532, +0.923879532511286756128183189396788286822416626);
DVK(KP408248290, +0.408248290463863016366214012450981898660991247);
DVK(KP414213562, +0.414213562373095048801688724209698078569671875);
DVK(KP816496580, +0.816496580927726032732428024901963797321982494);
DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
{
{
V T5, TH, Td, Tp, TE, Tq, T8, TG, Tc, Tk, TD, Ty;
{
V T1, T2, T3, T4;
T1 = LD(&(I[48]), 1, &(I[16]));
T2 = LD(&(I[80]), 1, &(I[16]));
T3 = LD(&(I[176]), 1, &(I[16]));
T4 = VADD(T2, T3);
T5 = VFMA(LDK(KP500000000), T4, T1);
TH = VSUB(T1, T4);
Td = VSUB(T3, T2);
}
{
V Tl, Tm, Tn, To;
Tl = LD(&(I[96]), 1, &(I[0]));
Tm = LD(&(I[160]), 1, &(I[0]));
Tn = LD(&(I[32]), 1, &(I[0]));
To = VSUB(Tm, Tn);
Tp = VFNMS(LDK(KP500000000), To, Tl);
TE = VADD(Tl, To);
Tq = VADD(Tn, Tm);
}
{
V Ta, T6, T7, Tb;
Ta = LD(&(I[144]), 1, &(I[16]));
T6 = LD(&(I[112]), 1, &(I[16]));
T7 = LD(&(I[16]), 1, &(I[16]));
Tb = VSUB(T6, T7);
T8 = VADD(T6, T7);
TG = VADD(Tb, Ta);
Tc = VFMS(LDK(KP500000000), Tb, Ta);
}
{
V Tg, Th, Ti, Tj;
Tg = LD(&(I[64]), 1, &(I[0]));
Th = LD(&(I[0]), 1, &(I[0]));
Ti = LD(&(I[128]), 1, &(I[0]));
Tj = VFMA(LDK(KP707106781), Ti, Th);
Tk = VFMA(LDK(KP816496580), Tj, Tg);
TD = VFMS(LDK(KP707106781), Th, Ti);
Ty = VFMS(LDK(KP816496580), Tj, Tg);
}
{
V TF, TI, TJ, TK;
TF = VFNMS(LDK(KP707106781), TE, TD);
TI = VFNMS(LDK(KP414213562), TH, TG);
ST(&(O[16]),VMUL(LDK(KP408248290), VFNMS(LDK(KP923879532), TI, TF)),1,&(O[16]));
ST(&(O[160]),VMUL(LDK(KP408248290), VFMA(LDK(KP923879532), TI, TF)),1,&(O[0]));
TJ = VFMA(LDK(KP707106781), TE, TD);
TK = VFMA(LDK(KP414213562), TG, TH);
ST(&(O[64]),VMUL(LDK(KP408248290), VFNMS(LDK(KP923879532), TK, TJ)),1,&(O[0]));
ST(&(O[112]),VMUL(LDK(KP408248290), VFMA(LDK(KP923879532), TK, TJ)),1,&(O[16]));
}
{
V Ts, Tu, Tf, Tt, Tr, T9, Te;
Tr = VFMA(LDK(KP866025403), Tq, Tp);
Ts = VFMA(LDK(KP816496580), Tr, Tk);
Tu = VFNMS(LDK(KP816496580), Tr, Tk);
T9 = VFMA(LDK(KP866025403), T8, T5);
Te = VFMA(LDK(KP866025403), Td, Tc);
Tf = VFNMS(LDK(KP414213562), Te, T9);
Tt = VFMA(LDK(KP414213562), T9, Te);
ST(&(O[176]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP937379142), Ts, Tf))),1,&(O[16]));
ST(&(O[96]),VMUL(LDK(KP377172239), VFMA(LDK(KP937379142), Tu, Tt)),1,&(O[0]));
ST(&(O[0]),VMUL(LDK(KP377172239), VFMA(LDK(KP937379142), Ts, Tf)),1,&(O[0]));
ST(&(O[80]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP937379142), Tu, Tt))),1,&(O[16]));
}
{
V TA, TC, Tx, TB, Tz, Tv, Tw;
Tz = VFNMS(LDK(KP866025403), Tq, Tp);
TA = VFMA(LDK(KP816496580), Tz, Ty);
TC = VFNMS(LDK(KP816496580), Tz, Ty);
Tv = VFNMS(LDK(KP866025403), T8, T5);
Tw = VFNMS(LDK(KP866025403), Td, Tc);
Tx = VFNMS(LDK(KP414213562), Tw, Tv);
TB = VFMA(LDK(KP414213562), Tv, Tw);
ST(&(O[48]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP937379142), TA, Tx))),1,&(O[16]));
ST(&(O[144]),VMUL(LDK(KP377172239), VFMA(LDK(KP937379142), TC, TB)),1,&(O[16]));
ST(&(O[128]),VMUL(LDK(KP377172239), VFMA(LDK(KP937379142), TA, Tx)),1,&(O[0]));
ST(&(O[32]),VNEG(VMUL(LDK(KP377172239), VFNMS(LDK(KP937379142), TC, TB))),1,&(O[0]));
}
}
}
VLEAVE();}

