#!/usr/bin/env bash
set -Eeuo pipefail

# Reproduced against FFTW genfft commit 93ed4c786934aec9946f8dda4b4e3eb08f8be41c.
export LC_ALL=C

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "usage: $0 /path/to/gen_r2r.native [output-directory]" >&2
    exit 2
fi

generator=$1
output_dir=${2:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../src/cpu/bm" && pwd)}
[[ -x "$generator" ]] || { echo "gen_r2r.native is not executable: $generator" >&2; exit 2; }
[[ -d "$output_dir" ]] || { echo "output directory is missing: $output_dir" >&2; exit 2; }

generate_one() {
    local n=$1
    local direction=$2
    local stride=$3
    local transform name output raw
    if [[ "$direction" == fwd ]]; then
        transform=-redft10
    else
        transform=-redft01
    fi
    name="nss_dct${n}_${direction}_is${stride}"
    output="$output_dir/dct_codelet_${direction}_n${n}_is${stride}.hpp"
    raw=$(mktemp "${TMPDIR:-/tmp}/nss-dct-codelet.XXXXXX")
    trap 'rm -f -- "$raw"' RETURN
    "$generator" -fma -simd -vneg -compact -variables 4 -pipeline-latency 4 \
        "$transform" -n "$n" -name "$name" -standalone -noloop \
        -with-istride "$stride" -with-ostride "$stride" \
        -with-ivstride 1 -with-ovstride 1 -unitary -normsqr "$((2 * n))" >"$raw"
    {
        printf '%s\n' '/*'
        printf '%s\n' ' * Copyright (c) 1997-1999 Massachusetts Institute of Technology'
        printf '%s\n' ' * Copyright (c) 2003, 2007-14 Matteo Frigo'
        printf '%s\n' ' * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology'
        printf '%s\n' ' *'
        printf '%s\n' ' * Generated by FFTW genfft and distributed under GNU GPL v2 or later.'
        printf '%s\n' ' * Do not edit by hand; regenerate with tools/gen_dct_codelets.sh.'
        printf '%s\n' ' */'
        awk '
            /^void nss_dct/ {
                sub(/^void /, "template <class D>\nstatic HWY_INLINE void ")
                sub(/\(const R \* I, R \* O\)/, "(D d, const R * I, R * O)")
            }
            { print }
        ' "$raw"
    } >"$output"
    rm -f -- "$raw"
    trap - RETURN
}

for n in 12 16 32 64; do
    for direction in fwd inv; do
        for stride in 8 16; do
            generate_one "$n" "$direction" "$stride"
        done
    done
done
